# Generated by Django 5.1.5 on 2025-02-02 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0003_teacher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp1.teacher",
            ),
        ),
    ]
